apiVersion: v1
kind: Service
metadata:
  # This service only exists to create DNS entries for each pod in the stateful
  # set such that they can resolve each other's IP addresses. It does not
  # create a load-balanced ClusterIP and should not be used directly by clients
  # in most circumstances.
  name: {{ template "aaf.fullname" . }}
  labels:
    app: {{ template "aaf.name" . }}
    chart: {{ template "aaf.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: {{ template "aaf.name" . }}
    release: {{ .Release.Name }}
