{{- if .Values.lb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "aaf.fullname" . }}-lb
  labels:
    app: {{ template "aaf.name" . }}
    chart: {{ template "aaf.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.lb.type }}
  selector:
    app: {{ template "aaf.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
{{- end }}
